### ISSUE TITLE
Некакдела

### ISSUE THREAD

**Issue by don-rumata** [kryzhovnik/neprivet#4]
А можно то же самое, но с перломутровыми пуговицами^W^W^W про то что не надо спрашивать "кагдила"?

**Comment by kryzhovnik** [comment]
Думаю, нет. "Как дела" - это немного про другое, эту фразу часто можно интерпретировать как "Хочешь сейчас поболтать?", то есть она про дружеское общение, трёп. Этот же текст, в большей степени касается делового общения.
